name: crt-post-promote-production

on:
  repository_dispatch:
    types:
      - crt-post-promote-production
      - crt-post-promote-production::*

permissions:
  actions: write

jobs:
  start-registry-check:
    name: Start Registry Check
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner
        uses: step-security/harden-runner@a5ad31d6a139d249332a2605b85202e8c0b78450 # v2.19.1
        with:
          use-policy-store: true
          api-key: ${{ secrets.STEP_SECURITY_API_KEY }}

      - name: Initiate Workflow
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh workflow run \
            --repo ${{ github.repository }} \
            --ref main \
            --field version=${{ github.event.client_payload.payload.version }} \
            registry-check.yml
  create-update-changelog-pr:
    name: Create Update Changelog PR
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner
        uses: step-security/harden-runner@a5ad31d6a139d249332a2605b85202e8c0b78450 # v2.19.1
        with:
          use-policy-store: true
          api-key: ${{ secrets.STEP_SECURITY_API_KEY }}

      - name: Initiate Workflow
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh workflow run \
            --repo ${{ github.repository }} \
            --ref main \
            --field previous_version=${{ github.event.client_payload.payload.version }} \
            update-changelog.yml
  post-publish:
    name: Runs post publish actions
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner
        uses: step-security/harden-runner@a5ad31d6a139d249332a2605b85202e8c0b78450 # v2.19.1
        with:
          use-policy-store: true
          api-key: ${{ secrets.STEP_SECURITY_API_KEY }}

      - name: Initiate Workflow
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh workflow run \
            --repo ${{ github.repository }} \
            --ref main \
            --field release_tag=${{ github.event.client_payload.payload.version }} \
            post-publish.yml
