name: 'Process milestone Events'

on:
  milestone:
    types: [closed]

permissions:
  issues: write
  pull-requests: write

jobs:
  Comment:
    name: 'Post-Release Comment'
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner
        uses: step-security/harden-runner@ab7a9404c0f3da075243ca237b5fac12c98deaa5 # v2.19.3
        with:
          use-policy-store: true
          egress-policy: audit
          api-key: ${{ secrets.STEP_SECURITY_API_KEY }}

      - uses: bflad/action-milestone-comment@4618cbf8bf938d31af1c576beeaaa77f486f5af3 # v2.0.0
        with:
          body: |
            This functionality has been released in [${{ github.event.milestone.title }} of the Terraform AWS Provider](https://github.com/${{ github.repository }}/blob/${{ github.event.milestone.title }}/CHANGELOG.md).  Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.

            For further feature requests or bug reports with this functionality, please create a [new GitHub issue](https://github.com/${{ github.repository }}/issues/new/choose) following the template. Thank you!

  archive_and_unlabel:
    name: 'Archive Project Items & Remove Label on Milestone Closed'
    runs-on: ubuntu-latest
    env:
      MILESTONE: ${{ github.event.milestone.number }}
    steps:
      - name: Harden the runner
        uses: step-security/harden-runner@ab7a9404c0f3da075243ca237b5fac12c98deaa5 # v2.19.3
        with:
          use-policy-store: true
          egress-policy: audit
          api-key: ${{ secrets.STEP_SECURITY_API_KEY }}

      - name: 'Checkout Repo'
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

      - name: 'Remove Prioritized Label'
        env:
          GH_TOKEN: ${{ github.token }}
        shell: bash
        run: ./.ci/scripts/unlabel-on-milestone-closed.sh

      - name: 'Archive Project Items'
        env:
          GH_TOKEN: ${{ secrets.PROJECT_SCOPED_TOKEN }}
        shell: bash
        run: ./.ci/scripts/archive-on-milestone-closed.sh
