name: Post Publish

on:
  workflow_dispatch:
    inputs:
      release_tag:
        type: string
        description: 'Semver release tag e.g. 1.1.0 (v prefix will be added automatically)'
        required: true

jobs:
  tidy-jira:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner
        uses: step-security/harden-runner@ab7a9404c0f3da075243ca237b5fac12c98deaa5 # v2.19.3
        with:
          use-policy-store: true
          egress-policy: audit
          api-key: ${{ secrets.STEP_SECURITY_API_KEY }}

      - name: Tidy Jira
        uses: breathingdust/github-jira-tidy@302d16f9cc705ea132dc20c34d1cff6a98b03509 # v0.15.0
        with:
          jira_host: 'hashicorp.atlassian.net'
          jira_username: 'sdavis@hashicorp.com'
          jira_password: ${{ secrets.jira_password }}
          jira_jql_filter: ${{ secrets.jira_jql_filter }}
          jira_github_url_field_id: 'cf[10089]'
          github_release_name: v${{ github.event.inputs.release_tag }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
